Src_include_module_test2 := C:/git/TESTPR~1/TESTPR~1 
Src_cppflags_module_test2 := 
#Src_cppflags_tgt_module_test2 :=
#Src_cflags_tgt_module_test2 :=
BUFFER_SIZE := 10240
COMM_BUFFER_INTEGRITY := false
COMM_CHECKSUM := false
COMM_FILE_COMPRESSION := false
COMPILER_INCLUDES := C:/PROGRA~1/Razorcat/TESSY_4.2/bin
COMPILER_INSTALL_PATH := C:/PROGRA~1/Razorcat/Shared/1.3/msys32
ENABLE_EXCEPTIONS := true
ENDIANESS := -
EXEFILE_EXTENSION := .exe
OBJFILE_EXTENSION := .o
TARGET_INSTALL_PATH := C:/PROGRA~1/Razorcat/TESSY_4.2/bin
TIMER_ENABLED := false
TIMER_FILE := C:/PROGRA~1/Razorcat/TESSY_4.2/sys/src/comm/TS_TIM~2.C
